### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by johnwp** [notTamion/DiscordConnector#6]
Hi Tamion, thanks for creating DiscordConnector!

This step #2 isn't clear to me. I updated the bot token and guild ID in `papermc/plugins/DiscordConnector-main/src/main/resources/plugin.yml`.

Do I also need to edit `papermc/permissions.yml`?

> Required Setup
> Start the server and set bot token and guild ID by using commands for which you will need the permissions DiscordConnector.token and DiscordConnector.id or directly editing the config

**Comment by notTamion** [comment]
Hey John.
No the permissions DiscordConnector.token and DiscordConnector.id are needed to use the commands /setbottoken and /setguildid. I just realized i am not acutally mentioning these commands in the documentation. Thanks for making me aware of this issue.
I hope i was able to clear up any confusion

**Comment by notTamion** [comment]
I will update the documentation when i have the time to do so
